site_name: Pan3D Documentation
theme: 'material'
plugins:
  - search
  - mkdocstrings
nav:
  - Home: README.md
  - Tutorials:
    - Pan3D Viewer: tutorials/dataset_viewer.md
    - Pan3D Command Line: tutorials/local_server.md
    - Jupyter Notebooks: tutorials/jupyter_notebook.md
  - API:
    - Dataset Builder: api/dataset_builder.md
    - Dataset Viewer: api/dataset_viewer.md
    - Configuration Files: api/configuration.md
