name: Publish Docker Packages
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  pan3d-geotrame:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: kitware/trame:pan3d-geotrame

  pan3d-cloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/cloud.Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: kitware/trame:pan3d-cloud
